# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c5111f9cb8d902ea89888a1e97bf542931e953b90130c619c1ab99bfb0bc7ad3f2b2a4ccde32c061f4abd175484541fb628501692dddadf4e06524e4ff086b
  secret_token: 7f2308ab1dbeba71b6af412e28ef2780c88a133a615b1d62f335d9d56c4369764fbf8b9c9cb17d2e562be52e45bd17d1f5c3a7febdb0890ce6786fccb7a6ebd3

test:
  secret_key_base: 0e171c5a834e60b3c60848bad732c5da318fcbdbfcc29ce721de32b984708bdd7c9d74e8ea6b1d61648d49d67442a12f2057020d03a6caae7186a83062d44c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
